---
- name: CoreOS
  hosts: coreos
  gather_facts: false
  roles:
    - defunctzombie.coreos-bootstrap

- name: Docker Manager
  hosts: docker-manager
  gather_facts: true
  roles:
    - docker-swarm

- name: Docker Worker
  hosts: docker-worker
  gather_facts: true
  roles:
    - docker-swarm

